-- CreateEnum
CREATE TYPE "TipoMovimiento" AS ENUM ('ENTRADA_POR_COMPRA', 'SALIDA_POR_ORDEN', 'AJUSTE_INVENTARIO', 'TRANSFERENCIA');

-- AlterTable
ALTER TABLE "Caja" ALTER COLUMN "saldo_inicial" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "saldo_actual" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "conteo_fisico" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "diferencia" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "fecha_apertura" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "fecha_cierre" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "CertificadoFiscal" ALTER COLUMN "vigencia_desde" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "vigencia_hasta" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Cita" ALTER COLUMN "fecha" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Cliente" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Cotizacion" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "fecha_validez" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "CotizacionDetalle" ALTER COLUMN "precio_unitario" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Diagnostico" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "FacturaFiscal" ALTER COLUMN "fecha_timbrado" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "FacturaFiscalDetalle" ALTER COLUMN "cantidad" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "precio_unitario" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "importe" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "Inventario" ALTER COLUMN "precio_promedio" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Marca" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Modelo" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "MovimientoCaja" ALTER COLUMN "monto" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "saldo_anterior" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "saldo_nuevo" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "MovimientoInventario" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "NotificacionTaller" ALTER COLUMN "fecha_lectura" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "OrdenCompra" ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "fecha_pedido" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "fecha_recibido" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "OrdenCompraDetalle" ALTER COLUMN "precio_unitario" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "descuento" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "subtotal" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "iva" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total" SET DATA TYPE DECIMAL(65,30);

-- AlterTable
ALTER TABLE "OrdenTrabajo" ALTER COLUMN "total_estimado" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "total_real" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "fecha_inicio" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "fecha_fin" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Pago" ALTER COLUMN "monto" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Proveedor" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "RecepcionVehiculo" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Refaccion" ALTER COLUMN "precio" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "costo" SET DATA TYPE DECIMAL(65,30),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "Rol" ALTER COLUMN "es_global" SET DEFAULT false;

-- AlterTable
ALTER TABLE "TiempoTecnico" ALTER COLUMN "hora_inicio" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "hora_fin" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);

-- AlterTable
ALTER TABLE "UsuarioEmpresa" ADD COLUMN     "es_propietario" BOOLEAN NOT NULL DEFAULT false;

-- AlterTable
ALTER TABLE "Vehiculo" ALTER COLUMN "created_at" SET DATA TYPE TIMESTAMP(3),
ALTER COLUMN "updated_at" SET DATA TYPE TIMESTAMP(3);
